require "settings"
require "mappings"
require "statusline"
require "plugins"
require "plugins.colorscheme"
require "plugins.telescope"
require "plugins.treesitter"
require "plugins.lsp"
require "plugins.cmp"
require "plugins.snippy"
require "plugins.lsp_signature"
-- require "plugins.haskell-vim"
require "plugins.lua-tree"
require "plugins.lualine"
